services:
  open-dynamic-export:
    build:
      args:
        DEBUG: "true"
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    command: ["node","--inspect=0.0.0.0:9229","dist/src/server/app.js"]