services:
  csip-dynamic-export:
    image: antonciu/csip-dynamic-export:v1.1
    build:
      context: .
      dockerfile: ./Dockerfile
    privileged: true # access to USB devices
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:3000
    volumes:
      - ./config/:/app/config/
      - ./logs/:/app/logs/
    restart: 'unless-stopped'
    # depends_on:
    #   - influxdb

  # influxdb:
  #   image: influxdb:2
  #   env_file:
  #     - .env
  #   ports:
  #     - ${INFLUXDB_PORT}:${INFLUXDB_PORT}
  #   environment:
  #     DOCKER_INFLUXDB_INIT_MODE: setup
  #     INFLUXD_HTTP_BIND_ADDRESS: :${INFLUXDB_PORT}
  #     DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
  #     DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
  #     DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
  #     DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
  #     DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
  #   volumes:
  #     - influxdb2-data:/var/lib/influxdb2
  #     - influxdb2-config:/etc/influxdb2
  #   restart: 'unless-stopped'
volumes:
  influxdb2-data:
  influxdb2-config: